<?php
	$locale = Mage::app()->getLocale()->getLocaleCode();
	$enabled	=	 Mage::getStoreConfig('pageslider/settings/enabled');	
	$imagewidth	=	 Mage::getStoreConfig('pageslider/settings/imagewidth');	
	$slidingtime	=	 Mage::getStoreConfig('pageslider/settings/slidingtime');
	$slidingtime = ($slidingtime*1000);
	$slidereffect =Mage::getStoreConfig('pageslider/settings/slidereffect');
		
	// Get IMAGE COLLECTION
	$imageCollection = $this->getImageCollection();	
	
	// Get page number
	$pageNum=ceil(count($imageCollection)/4);
	?>

<?php if($enabled){?>
<?php if(count($imageCollection)){?>

<link  rel="stylesheet" href="<?php echo $this->getSkinUrl('pageslider/css/style.css') ?>" type="text/css" media="screen"/>
<!-- If jquery alredy loaded then below jQuery file not required -->
<style type="text/css">
.cn_wrapper {
	width:<?php echo $imagewidth;?>px
}
.cn_content,.cn_content img{width:<?php echo $imagewidth-280;?>px}
.cn_preview{width:<?php echo $imagewidth-250;?>px}
</style>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pageslider/js/cufon-yui.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pageslider/js/Bebas_400.font.js') ?>"></script>
<script type="text/javascript">
			Cufon('.cn_wrapper h1,h2', {
				textShadow: '-1px 1px black'
			});
		</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pageslider/js/jquery.easing.1.3.js') ?>"></script>
<script type="text/javascript">
            $(function() {
                //caching
				//next and prev buttons
				var $cn_next	= $('#cn_next');
				var $cn_prev	= $('#cn_prev');
				//wrapper of the left items
				var $cn_list 	= $('#cn_list');
				var $pages		= $cn_list.find('.cn_page');
				//how many pages
				var cnt_pages	= $pages.length;
				//the default page is the first one
				var page		= 1;
				//list of news (left items)
				var $items 		= $cn_list.find('.cn_item');
				//the current item being viewed (right side)
				var $cn_preview = $('#cn_preview');
				//index of the item being viewed. 
				//the default is the first one
				var current		= 1;
				
				/*
				for each item we store its index relative to all the document.
				we bind a click event that slides up or down the current item
				and slides up or down the clicked one. 
				Moving up or down will depend if the clicked item is after or
				before the current one
				*/
				$items.each(function(i){
					var $item = $(this);
					$item.data('idx',i+1);
					
					$item.bind('click',function(){
						var $this 		= $(this);
						$cn_list.find('.selected').removeClass('selected');
						$this.addClass('selected');
						var idx			= $(this).data('idx');
						var $current 	= $cn_preview.find('.cn_content:nth-child('+current+')');
						var $next		= $cn_preview.find('.cn_content:nth-child('+idx+')');
						
						if(idx > current){
							$current.stop().animate({'top':'-300px'},<?php echo $slidingtime;?>,'<?php echo $slidereffect;?>',function(){
								$(this).css({'top':'310px'});
							});
							$next.css({'top':'310px'}).stop().animate({'top':'5px'},<?php echo $slidingtime;?>,'<?php echo $slidereffect;?>');
						}
						else if(idx < current){
							$current.stop().animate({'top':'310px'},<?php echo $slidingtime;?>,'<?php echo $slidereffect;?>',function(){
								$(this).css({'top':'310px'});
							});
							$next.css({'top':'-300px'}).stop().animate({'top':'5px'},<?php echo $slidingtime;?>,'<?php echo $slidereffect;?>');
						}
						current = idx;
					});
				});
				
				/*
				shows next page if exists:
				the next page fades in
				also checks if the button should get disabled
				*/
				$cn_next.bind('click',function(e){
					var $this = $(this);
					$cn_prev.removeClass('disabled');
					++page;
					if(page == cnt_pages)
						$this.addClass('disabled');
					if(page > cnt_pages){ 
						page = cnt_pages;
						return;
					}	
					$pages.hide();
					$cn_list.find('.cn_page:nth-child('+page+')').fadeIn();
					e.preventDefault();
				});
				/*
				shows previous page if exists:
				the previous page fades in
				also checks if the button should get disabled
				*/
				$cn_prev.bind('click',function(e){
					var $this = $(this);
					$cn_next.removeClass('disabled');
					--page;
					if(page == 1)
						$this.addClass('disabled');
					if(page < 1){ 
						page = 1;
						return;
					}
					$pages.hide();
					$cn_list.find('.cn_page:nth-child('+page+')').fadeIn();
					e.preventDefault();
				});
				
            });
        </script>

<div class="cn_wrapper">
  <div id="cn_preview" class="cn_preview">
    <?php foreach ($imageCollection as $key=>$banner): ?>
    <div class="cn_content" <?php if($key==0) {?>style="top:5px;"<?php }?> > <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."bsimages/".$banner['filename']?>" alt=""/>
      <h1><?php echo $banner['slider_title'];?></h1>
      <p><?php echo $banner['slider_content'];?></p>
      <a href="<?php echo $banner['weblink'];?>" target="_blank" class="cn_more">Read more</a> </div>
    <?php endforeach; ?>
  </div>
  <div id="cn_list" class="cn_list">
    <?php for ($i = 0; $i < $pageNum; $i++) { ?>
    <div class="cn_page" <?php if ($i==0){?> style="display:block;" <?php }?>>
      <?php for ($j= $i*4; $j < ($i+1)*4; $j++)  {      
      	if ($j==count($imageCollection)){      		
      		break;
      	}
      	else{
      	?>
      <div class="cn_item <?php if($j==0) {?>selected<?php }?>">
        <h2><?php echo $imageCollection[$j]['page_title'];?></h2>
        <p><?php echo $imageCollection[$j]['page_content'];?></p>
      </div>
      <?php }}?>
    </div>
    <?php } ?>
    <div class="cn_nav"> <a id="cn_prev" class="cn_prev disabled"></a> <a id="cn_next" class="cn_next"></a> </div>
  </div>
</div>
<div style="clear:both; display:block;"></div>
<?php }else{
	echo "<p><b>Upload Slider.</b></p><p>Please upload slider images.</p>";
} ?>
<?php }?>
